import { ServiceDurationOption } from "~/features/garage/types/serviceDurationOption";

export const SERVICE_DURATION_OPTIONS = [
  { value: 0, type: "day", daysNumber: 0 },
  { value: 1, type: "day", daysNumber: 1 },
  { value: 2, type: "day", daysNumber: 2 },
  { value: 3, type: "day", daysNumber: 3 },
  { value: 4, type: "day", daysNumber: 4 },
  { value: 5, type: "day", daysNumber: 5 },
  { value: 6, type: "day", daysNumber: 6 },
  { value: 7, type: "day", daysNumber: 7 },
  { value: 14, type: "day", daysNumber: 14 },
  { value: 21, type: "day", daysNumber: 21 },
  { value: 28, type: "day", daysNumber: 28 },
  { value: 1, type: "month", daysNumber: 30 },
  { value: 2, type: "month", daysNumber: 60 },
  { value: 3, type: "month", daysNumber: 90 },
  { value: 4, type: "month", daysNumber: 120 },
  { value: 5, type: "month", daysNumber: 150 },
  { value: 6, type: "month", daysNumber: 180 },
  { value: 9, type: "month", daysNumber: 270 },
  { value: 1, type: "year", daysNumber: 365 },
  { value: 2, type: "year", daysNumber: 730 },
  { value: 3, type: "year", daysNumber: 1095 },
  { value: 4, type: "year", daysNumber: 1460 },
  { value: 5, type: "year", daysNumber: 1825 },
  { value: 6, type: "year", daysNumber: 2190 },
  { value: 7, type: "year", daysNumber: 2555 },
  { value: 8, type: "year", daysNumber: 2920 },
  { value: 9, type: "year", daysNumber: 3285 },
  { value: 10, type: "year", daysNumber: 3650 },
] satisfies ServiceDurationOption[];
